name: 'GitHub Actions CSDN Email Bot'

on:
  schedule:
    - cron: '* 1/3 * * *'
jobs:
  csdn-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
      - name: 'Install lib'
        run: pip install -r ./csdn-emailbot/requirements.txt
      - name: 'Working'
        run: bash ./csdn-emailbot/main.sh
